### spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath*:com/bysj/mapper/*Mapper.xml
  type-aliases-package: com.bysj.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl